name: record_mp3_example
description: Demonstrates how to use the record_mp3_plus plugin.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  audioplayers: ^6.0.0
  flutter_desktop_audio_recorder: ^0.0.1
  record_mp3_plus:
    path: ../

dependency_overrides:
  # https://github.com/Baseflow/flutter-permission-handler/pull/1207
  permission_handler:
    git:
      url: git@github.com:alex-melnyk/flutter-permission-handler.git
      path: permission_handler
      ref: master
  # https://github.com/Baseflow/flutter-permission-handler/pull/1207
  permission_handler_apple:
    git:
      url: git@github.com:alex-melnyk/flutter-permission-handler.git
      path: permission_handler_apple
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
