name: record_mp3
description: Record an MP3 using the Platform native APIï¼ŒYou can start ,pause,resume and stop record,And export an MP3 file.
version: 1.0.0
homepage: https://github.com/amorenew/record_mp3_plus
publish_to: https://pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.16.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.plugin.record_mp3
        pluginClass: RecordMp3Plugin
      ios:
        pluginClass: RecordMp3Plugin
      macos:
        pluginClass: RecordMp3Plugin
